# based on https://github.com/harendra-kumar/xls/blob/master/.travis.yml

language: c
sudo: false
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.local
  - $HOME/.stack

matrix:
  include:
  # cabal/linux
  - env: BUILD=cabal GHCVER=7.8.4 CABALVER=1.18
    addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=head CABALVER=head
    addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  # stack/linux
  - env: BUILD=stack RESOLVER=lts-6
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack RESOLVER=nightly
    addons: {apt: {packages: [libgmp-dev]}}

  # cabal/stack/osx
  - env: BUILD=cabal RESOLVER=lts-6
    os: osx

  - env: BUILD=stack RESOLVER=lts-6
    os: osx

  allow_failures:
  - env: BUILD=cabal GHCVER=head CABALVER=head
  - env: BUILD=stack RESOLVER=nightly

install: true
script:
  - |
    set_tool_path()  { eval "test -n \"\$$1\"" && eval "PATH=/opt/$2/\"\$$1\"/bin:$PATH"; true; }
    when_cabal() { if test "$BUILD" = cabal; then echo $1; fi; }
    script_url() { echo https://raw.githubusercontent.com/harendra-kumar/package-test/$1/package-test.sh; }

    CURL=$(which curl)
    PATH=/bin:/usr/bin
    # Add appropriate ghc and cabal versions from /opt to PATH
    set_tool_path GHCVER   ghc
    set_tool_path CABALVER cabal

  - env -i
      PATH=$PATH
      BUILD=$BUILD
      RESOLVER=$RESOLVER
      GHCVER=$GHCVER
      CABALVER=$CABALVER
      GHC_OPTIONS="-O0 -Werror"
      $(when_cabal CABAL_TEST_INSTALL=y)
      $(when_cabal CABAL_NO_SANDBOX=y)
      $(when_cabal CABAL_HACKAGE_MIRROR=hackage.haskell.org:http://hackage.fpcomplete.com)
      /bin/bash <($CURL -sL $(script_url f47abfb22fbdfb41668a2d3032353b06c87636f2))
