# based on https://github.com/harendra-kumar/xls/blob/master/.travis.yml

language: c
sudo: false
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.local
  - $HOME/.stack

matrix:
  include:
  # stack/linux
  - env: BUILD=stack STACK_YAML=stack-7.8.yaml
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack STACK_YAML=stack-7.10.yaml
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack STACK_YAML=stack-8.0.yaml
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack STACK_YAML=stack-8.2.yaml
    addons: {apt: {packages: [libgmp-dev]}}

  # cabal/stack/osx
  - env: BUILD=stack STACK_YAML=stack-7.8.yaml
    os: osx

  - env: BUILD=stack STACK_YAML=stack-7.10.yaml
    os: osx

  - env: BUILD=stack STACK_YAML=stack-8.0.yaml
    os: osx

  - env: BUILD=stack STACK_YAML=stack-8.2.yaml
    os: osx

install: true
script:
  - |
    set_tool_path()  { eval "test -n \"\$$1\"" && eval "PATH=/opt/$2/\"\$$1\"/bin:$PATH"; true; }
    when_cabal() { if test "$BUILD" = cabal; then echo $1; fi; }
    script_url() { echo https://raw.githubusercontent.com/harendra-kumar/package-test/$1/package-test.sh; }

    CURL=$(which curl)
    PATH=/bin:/usr/bin
    # Add appropriate ghc and cabal versions from /opt to PATH
    set_tool_path GHCVER   ghc
    set_tool_path CABALVER cabal

  - env -i
      PATH=$PATH
      BUILD=$BUILD
      RESOLVER=$RESOLVER
      GHCVER=$GHCVER
      CABALVER=$CABALVER
      GHC_OPTIONS="-O0"
      $(when_cabal CABAL_TEST_INSTALL=y)
      $(when_cabal CABAL_NO_SANDBOX=y)
      $(when_cabal CABAL_HACKAGE_MIRROR=hackage.haskell.org:http://hackage.fpcomplete.com)
      /bin/bash <($CURL -sL $(script_url f47abfb22fbdfb41668a2d3032353b06c87636f2))
